export const foodData = [
    {
        id: 1,
        Name: "Harira",
        category: "lunch",
        dsc: "Harira au Thermomix",
        price: 12,
        img: "https://img.cuisineaz.com/312x250/2019/03/30/i146212-harira-au-thermomix.webp",
    },
    {
        id: 2,
        Name: "Tajine",
        category: "lunch",
        dsc: "Tajine de poulet aux épices",
        price: 89,
        img: "https://img.cuisineaz.com/660x660/2013/12/20/i79008-photo-de-tajine-de-poulet-aux-epices.webp",
    },
    {
        id: 3,
        Name: "Chicken Fricassee",
        category: "dinner",
        dsc: "Chicken Fricassée is a traditional French chicken stew made with browned chicken pieces braised in a creamy white mushroom sauce",
        price: 77,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAtnHt1epOPktHqQH-8WNNdpunkeOY-qP25Q&usqp=CAU",
    },
    {
        id: 4,
        Name: "Omlite",
        category: "breakfast",
        dsc: "Omelette in a white plate on wooden table",
        price: 12,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0XO_du6_XWTT6uuLNGgW0iJl0lhhXKYDMD8SWwjmcsg&s",
    },
    {
        id: 5,
        Name: "Pizza",
        category: "lunch",
        dsc: "",
        price: 12,
        img: "https://media-cdn.tripadvisor.com/media/photo-s/17/a6/c1/ba/photo2jpg.jpg",
    },
    {
        id: 6,
        Name: "Mediterranean Breakfast Bowls",
        category: "breakfast",
        dsc: "",
        price: 99,
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlWz214l1JRg1FC08PpRVVBPGLED71jzYUSQ&usqp=CAU",
    },

];
